name: Update YouTube Feed

on:
  schedule:
    # Chạy mỗi 6 giờ
    - cron: '0 */6 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-youtube:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate youtube.json
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          node update-youtube.js

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add youtube.json

          git diff --cached --quiet || (
            git commit -m "Auto update youtube.json"
            git push
          )
